name: Potentiality
favicon: null
layout_spectrum: 0.7238870477303863
typography_spectrum: 0.6725350713822991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9353877515532076
  lightness: 0.0689056059345603
  saturation: 0.40594239020720124
  rhythmicContrast: 0.9290210863109678
purpose: []
